-- Autogenerated schemas for reference.

--
-- Name: agency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.agency (
    index bigint,
    agency_id text,
    agency_name text,
    agency_url text,
    agency_fare_url text,
    agency_timezone text,
    agency_phone text
);


ALTER TABLE public.agency OWNER TO postgres;

--
-- Name: routes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.routes (
    index bigint,
    route_id bigint,
    agency_id text,
    route_short_name text,
    route_long_name text,
    route_desc double precision,
    route_type bigint,
    route_color text,
    route_text_color text,
    route_url text
);


ALTER TABLE public.routes OWNER TO postgres;

--
-- Name: stop_times; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stop_times (
    index bigint,
    trip_id bigint,
    stop_sequence bigint,
    stop_id bigint,
    stop_headsign text,
    arrival_time text,
    departure_time text,
    pickup_type bigint,
    drop_off_type bigint,
    timepoint bigint,
    shape_dist_traveled double precision,
    fare_units_traveled bigint
);


ALTER TABLE public.stop_times OWNER TO postgres;

--
-- Name: stops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stops (
    index bigint,
    stop_id text,
    stop_code double precision,
    stop_name text,
    stop_lat double precision,
    stop_lon double precision,
    location_type bigint,
    parent_station text,
    stop_timezone text,
    wheelchair_boarding double precision,
    platform_code text
);


ALTER TABLE public.stops OWNER TO postgres;

--
-- Name: trips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.trips (
    index bigint,
    route_id bigint,
    service_id bigint,
    trip_id bigint,
    realtime_trip_id text,
    trip_headsign text,
    trip_short_name double precision,
    trip_long_name text,
    direction_id bigint,
    block_id double precision,
    shape_id double precision,
    wheelchair_accessible bigint,
    bikes_allowed double precision
);


ALTER TABLE public.trips OWNER TO postgres;

--
-- Name: ix_agency_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_agency_index ON public.agency USING btree (index);


--
-- Name: ix_routes_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_routes_index ON public.routes USING btree (index);


--
-- Name: ix_stop_times_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_stop_times_index ON public.stop_times USING btree (index);


--
-- Name: ix_stops_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_stops_index ON public.stops USING btree (index);


--
-- Name: ix_trips_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_trips_index ON public.trips USING btree (index);